//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP.Framework.ObjectModel.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPP.Framework.ObjectModel.Validation.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is invalid..
        /// </summary>
        internal static string DependentValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DependentValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression list contains an invalid expression of type {0}..
        /// </summary>
        internal static string ObjectValidator_Expression_Type_Is_Invalid {
            get {
                return ResourceManager.GetString("ObjectValidator_Expression_Type_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string RequiredIfAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredIfAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} cannot be validated against itself..
        /// </summary>
        internal static string UniqueAttribute_Property_Cannot_Validate_Against_Itself {
            get {
                return ResourceManager.GetString("UniqueAttribute_Property_Cannot_Validate_Against_Itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is invalid because it matches the value of field {1}..
        /// </summary>
        internal static string UniqueAttribute_ValidationError {
            get {
                return ResourceManager.GetString("UniqueAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source type {1} cannot be converted to destination type {0}..
        /// </summary>
        internal static string ValidationContext_Invalid_Destination_Type {
            get {
                return ResourceManager.GetString("ValidationContext_Invalid_Destination_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {1} does not define a property, field, or paramerless method with the name {0}..
        /// </summary>
        internal static string ValidationContext_Member_Is_Missing {
            get {
                return ResourceManager.GetString("ValidationContext_Member_Is_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {1}.{0} is write-only, and the value cannot be read..
        /// </summary>
        internal static string ValidationContext_Member_Is_WriteOnly {
            get {
                return ResourceManager.GetString("ValidationContext_Member_Is_WriteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member {0} must be defined as a property, field, or non-generic parameterless method by type {1} in order to be used for validation..
        /// </summary>
        internal static string ValidationContext_Member_Type_Is_Invalid {
            get {
                return ResourceManager.GetString("ValidationContext_Member_Type_Is_Invalid", resourceCulture);
            }
        }
    }
}
